use zerocopy::{AsBytes, FromBytes, FromZeroes};

/// 64-byte aligned header for the Disruptor.
#[repr(C, align(64))]
#[derive(FromZeroes, FromBytes, AsBytes, Debug)]
pub struct RingBufferHeader {
    pub write_cursor: u64,
    pub read_cursor: u64,
    pub capacity: u64,
    pub _reserved: [u8; 40],
}

/// 64-byte aligned Tick Event.
/// We order by size descending to minimize internal padding, 
/// then manually pad the end to 64 bytes.
#[repr(C, align(64))]
#[derive(FromZeroes, FromBytes, AsBytes, Debug, Clone, Copy)]
pub struct TickEvent {
    pub timestamp: f64,      // 8
    pub mid_price: f64,      // 8
    pub bid_depth: f64,      // 8
    pub ask_depth: f64,      // 8
    pub instrument_id: u16,  // 2
    pub exchange_id: u8,     // 1
    pub _pad1: [u8; 5],      // 5 (Align to 8 bytes)
    pub _reserved: [u8; 24], // 24 (Total 64)
}

/// Target state pushed from Python Brain to Rust Brawn.
#[repr(C, align(64))]
#[derive(FromZeroes, FromBytes, AsBytes, Debug, Clone, Copy)]
pub struct TargetState {
    pub timestamp: f64,         // 8
    pub target_q: f64,          // 8
    pub uncertainty_bound: f64, // 8
    pub instrument_id: u16,     // 2
    pub _pad1: [u8; 6],         // 6 (Align to 8 bytes)
    pub _reserved: [u8; 32],    // 32 (Total 64)
}

/// Pre-validated safety bounds generated by the Z3/Convex Brain.
/// The Brawn can fire optimistically as long as it stays within these bounds.
#[repr(C, align(64))]
#[derive(FromZeroes, FromBytes, AsBytes, Debug, Clone, Copy)]
pub struct SafetyEnvelope {
    pub timestamp: f64,          // 8
    pub max_notional_usd: f64,   // 8
    pub min_price_limit: f64,    // 8
    pub max_price_limit: f64,    // 8
    pub max_allowed_delta: f64,  // 8
    pub is_emergency_halt: u8,   // 1
    pub _pad1: [u8; 7],          // 7
    pub _reserved: [u8; 16],     // 16 (Total 64)
}
